In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.zeros([1])
np.random.rand(100).astype(np.float32)

array([ 0.5712775 ,  0.25790262,  0.22221889,  0.63457149,  0.45363918,
        0.84194487,  0.67679256,  0.54899532,  0.4827078 ,  0.98416692,
        0.50480366,  0.20039843,  0.70315117,  0.18738241,  0.29951182,
        0.97772431,  0.13056186,  0.32468143,  0.90810162,  0.00528852,
        0.9080053 ,  0.09456689,  0.93613136,  0.38795871,  0.12948939,
        0.56848472,  0.13036035,  0.74779379,  0.14863485,  0.77913219,
        0.18657476,  0.51091617,  0.0187392 ,  0.94430256,  0.66249448,
        0.93570101,  0.63483262,  0.74258894,  0.89211142,  0.00173194,
        0.0647627 ,  0.93764859,  0.27579531,  0.05901137,  0.05294634,
        0.37551796,  0.87892818,  0.38268259,  0.14045933,  0.94500756,
        0.8708716 ,  0.06860734,  0.61725897,  0.86418444,  0.90789479,
        0.64581364,  0.31438783,  0.47873968,  0.92901731,  0.00560958,
        0.45902219,  0.75698513,  0.68421775,  0.12440142,  0.80350602,
        0.64129645,  0.66839665,  0.62302727,  0.03623809,  0.02

In [4]:
x = tf.placeholder(tf.float32, shape=[None, 784])
x_image = tf.reshape(x, [-1,28,28,1])

In [5]:
x.get_shape()

TensorShape([Dimension(None), Dimension(784)])

In [6]:
x_image.get_shape()

TensorShape([Dimension(None), Dimension(28), Dimension(28), Dimension(1)])

In [4]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
np.reshape(a, (6))

array([0, 1, 2, 3, 4, 5])